### ISSUE TITLE
Have dota class inheret from an event class

### ISSUE THREAD

**Issue by LanceMaverick** [LanceMaverick/dotagram#1]
Need an event super-class to make it game (and event) independent.
### Features
- Can create multiple events instances  that persist simultaneously
- Bot users can define new events within chat, specifying participator limits and event name
- Inline features?
- Allows the creation of sub-classes such as the dota class. The custom class will be a 'feature light' subclass of event with the important features (shotgunning, readying up, specifying time, player limit etc). This means dota and other hard coded events can maintain the custom features (e.g posting friday night dota pictures when dota event is creating on a Friday, the custom bot messages etc)

**Comment by natfarleydev** [comment]
Happy to do this, I'll have a look tonight or tomorrow night. Inline features might be a stretch at this stage, might be worth creating another issue once this one is closed?

**Comment by natfarleydev** [comment]
I've classed out the event bit of the `dota` class with commit https://github.com/LanceMaverick/dotagram/commit/8595c92f7cea284852075ca3f93170de27c5d485.
